### ISSUE TITLE
is there a way to enforce tabs rather than spaces?

### ISSUE THREAD

**Issue by modernNeo** [LintlyCI/Flake8Rules#14]

**Comment by grantmcconnaughey** [comment]
To my knowledge Flake8 doesn't have configuration to lint for tabs, since PEP8 prefers spaces. You'll have to turn off [W191](https://lintlyci.github.io/Flake8Rules/rules/W191.html) if you don't want Flake8 to complain about the use of tabs. [E101](https://lintlyci.github.io/Flake8Rules/rules/E101.html) will also check if indentation and tabs are combined.

**Comment by modernNeo** [comment]
thanks
